on:
  push:
    branches:
      - '*'
      - '!master'

env:
  JIRA_BOARD_PREFIX: 'S2P'

jobs:
  check_jira_issue_on_branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: tj-actions/branch-names@v5.2
        id: branch-name

      - uses: actions-ecosystem/action-regex-match@v2
        id: find-jira-issue
        with:
          text: ${{ steps.branch-name.outputs.current_branch }}
          regex: '^.*(${{ env.JIRA_BOARD_PREFIX }}-\d+).*$'
      
      - run: echo "${{ steps.find-jira-issue.outputs.match }}"
      - run: echo "${{ steps.find-jira-issue.outputs.group1 }}"