name: Check JIRA issue

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited

env:
  ISSUE_ID_PATTERN: '[A-Z0-9][A-Z0-9]+-[0-9]+'

jobs:
  check_jira_issue_on_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: ${{ github.event.pull_request.commits }}

      - name: Get branch name
        uses: tj-actions/branch-names@v5.2
        id: branch-name
      
      - name: Get commit messages
        id: commit-messages
        run: |
          COMMIT_MESSAGES=$(git log --no-decorate --oneline --no-merges --abbrev-commit -n ${{ github.event.pull_request.commits }})
          echo "$COMMIT_MESSAGES"
          echo "COMMIT_MESSAGES<<EOF" >> $GITHUB_ENV
          echo "$COMMIT_MESSAGES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        
      - name: Show commit messages
        run: |
          echo "${{ env.COMMIT_MESSAGES }}"

      - name: Search JIRA issue id on branch name
        uses: actions-ecosystem/action-regex-match@v2
        id: branch-search
        with:
          text: ${{ steps.branch-name.outputs.current_branch }}
          regex: '^.*(${{ env.ISSUE_ID_PATTERN }}).*$'

      - name: Search JIRA issue id on PR title
        uses: actions-ecosystem/action-regex-match@v2
        id: pr-search
        with:
          text: ${{ github.event.pull_request.title }}
          regex: '^(${{ env.ISSUE_ID_PATTERN }}).*$'

      - name: Search JIRA issue id on commit messages
        uses: actions-ecosystem/action-regex-match@v2
        id: commits-search
        with:
          text: ${{ env.COMMIT_MESSAGES }}
          regex: '(${{ env.ISSUE_ID_PATTERN }})'

      - name: Check JIRA issue id
        uses: actions/github-script@v6
        if: ${{ steps.branch-search.outputs.group1 == '' && steps.pr-search.outputs.group1 == '' && steps.commits-search.outputs.group1 == '' }}
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ':warning: No JIRA issue id found in branch name, commits or PR title.',
            })
            process.exit(1)
      
      # - name: Check JIRA issue id
      #   if: ${{ steps.branch-search.outputs.group1 == '' }}
      #   run: |
      #     echo "No JIRA issue id found on branch name matching pattern '${{ env.ISSUE_ID_PATTERN }}'."
      #     exit 1