on:
  push:
    branches:
      - '*'
      - '!master'
      - '!main'

env:
  ISSUE_PREFIX: 'S2P'

jobs:
  check_jira_issue_on_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get branch name
        uses: tj-actions/branch-names@v5.2
        id: branch-name

      - name: Search JIRA issue id
        uses: actions-ecosystem/action-regex-match@v2
        id: search-jira-issue-id
        with:
          text: ${{ steps.branch-name.outputs.current_branch }}
          regex: '^.*(${{ env.ISSUE_PREFIX }}-\d+).*$'
      
      - name: Check JIRA issue id
        if: ${{ steps.search-jira-issue-id.outputs.group1 == '' }}
        run: |
          echo "No JIRA issue id found on branch name with prefix '${{ env.ISSUE_PREFIX }}-', ensure the ISSUE_PREFIX includes your board prefix."
          exit 1