on:
  workflow_dispatch:

jobs:
  publish_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: zwaldowski/semver-release-action@v2
        with:
          bump: minor
          prefix: v
          github_token: ${{ secrets.GITHUB_TOKEN }}
        id: create_tag
      - run: echo "${{ steps.create_tag.outputs.version }}"
